# Generated by Selenium IDE
from model.contact import Contact, BirthDate


def test_testAddAddress(app):
    app.session.login(username="admin", password="secret")
    bdate = BirthDate(bday="28", bmonth="June", byear="1971")
    contact = Contact(firstname="Elon", lastname="Musk", nickname="elona51", company="Tesla, SpaceX", address="California, Silicon Valley", birthDate=bdate, notes="Smart person (not an alian)")
    app.contact.add(contact)
    app.session.logout()
