# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from contact import Contact, BirthDate


class TestTestAddAddress:
    def setup_method(self, method):
        self.wd = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.wd.quit()

    def openHomePage(self):
        self.wd.get("http://localhost/addressbook/")

    def login(self):
        self.wd.find_element(By.NAME, "user").click()
        self.wd.find_element(By.NAME, "user").send_keys("admin")
        self.wd.find_element(By.NAME, "pass").send_keys("secret")
        self.wd.find_element(By.XPATH, "//input[@value='Login']").click()

    def openContactsForm(self):
        self.wd.find_element(By.LINK_TEXT, "add new").click()

    def addNewContact(self, contact):
        self.wd.find_element(By.NAME, "firstname").click()
        self.wd.find_element(By.NAME, "firstname").send_keys(contact.firstname)
        self.wd.find_element(By.NAME, "lastname").click()
        self.wd.find_element(By.NAME, "lastname").send_keys(contact.lastname)
        self.wd.find_element(By.NAME, "nickname").click()
        self.wd.find_element(By.NAME, "nickname").send_keys(contact.nickname)
        self.wd.find_element(By.NAME, "company").click()
        self.wd.find_element(By.NAME, "company").send_keys(contact.company)
        self.wd.find_element(By.NAME, "address").click()
        self.wd.find_element(By.NAME, "address").send_keys(contact.address)
        self.wd.find_element(By.NAME, "bday").click()
        dropdown = self.wd.find_element(By.NAME, "bday")
        dropdown.find_element(By.XPATH, f"//option[. = '{contact.birthDate.bday}']").click()
        self.wd.find_element(
            By.CSS_SELECTOR, "select:nth-child(61) > option:nth-child(15)"
        ).click()
        self.wd.find_element(By.NAME, "bmonth").click()
        dropdown = self.wd.find_element(By.NAME, "bmonth")
        dropdown.find_element(By.XPATH, f"//option[. = '{contact.birthDate.bmonth}']").click()
        self.wd.find_element(
            By.CSS_SELECTOR, "select:nth-child(62) > option:nth-child(7)"
        ).click()
        self.wd.find_element(By.NAME, "byear").click()
        self.wd.find_element(By.NAME, "byear").send_keys(contact.birthDate.byear)
        self.wd.find_element(By.NAME, "theform").click()
        self.wd.find_element(By.NAME, "notes").click()
        self.wd.find_element(By.NAME, "notes").send_keys(contact.notes)
        self.wd.find_element(By.XPATH, "(//input[@name='submit'])[2]").click()

    def returnToMainPage(self):
        self.wd.find_element(By.LINK_TEXT, "home page").click()

    def logout(self):
        self.wd.find_element(By.LINK_TEXT, "Logout").click()

    def test_testAddAddress(self):
        self.openHomePage()
        self.login()
        self.openContactsForm()
        bdate = BirthDate(bday="28", bmonth="June", byear="1971")
        contact = Contact(firstname="Elon", lastname="Musk", nickname="elona51", company="Tesla, SpaceX", address="California, Silicon Valley", birthDate=bdate, notes="Smart person (not an alian)")
        self.addNewContact(contact)
        self.returnToMainPage()
        self.logout()
